#!/usr/bin/env bash

set -eu

if [ $# -lt 1 ]; then
    echo "usage: $0 remotename [branch]" >&2
    exit 1
fi

remotename="$1"
branch="${2:-}"

git fetch --prune "$remotename"

rem_branches=$(
  git for-each-ref refs/remotes/"$remotename" --format='%(refname:lstrip=3)' --merged $branch | \
  egrep -v '(master|develop)'
)
if [[ -n $rem_branches ]]; then
  xargs git push "$remotename" --delete <<<"$rem_branches"
fi

loc_branches=$(
  git for-each-ref refs/heads --format='%(refname:lstrip=2)' --merged $branch | \
  egrep -v '(master|develop)'
)
if [[ -n $loc_branches ]]; then
  xargs git branch -d <<<"$loc_branches"
fi
